import type { Metadata } from 'next'
import './globals.css'
import localFont from 'next/font/local'
import Header from './components/Header'

const font = localFont({ src: './Clash_Regular.otf' })

export const metadata: Metadata = {
  title: 'Clash of Clans Tracker',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${font.className} antialiased`}>
        <main className="h-dvh">
          <Header />
          <div className="p-2">{children}</div>
        </main>
      </body>
    </html>
  )
}
